//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string UserName { get; set; }
        public Nullable<byte> IdRol { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public bool Estatus { get; set; }
        public string CURP { get; set; }
        public byte[] Imagen { get; set; }
        public Nullable<int> IdDireccion { get; set; }
    
        public virtual Direccion Direccion { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
